ebmdatalab/clinicaltrials-act-tracker

- clinicaltrials/templates/about.html
Updated some hyperlinks and added questions:
"I found a journal article/conference abstract/other document containing results from this study. Why are you saying it has unreported results?"
and
"This trial’s primary completion date has passed, but it has not yet reached its completion date. Why are you saying it is required to report?"
> Feb 21 About Page Updates

- clinicaltrials/frontend/models.py
- clinicaltrials/frontend/settings.py
- clinicaltrials/frontend/tests/test_models.py
- clinicaltrials/frontend/tests/test_views.py
- clinicaltrials/frontend/urls.py
- clinicaltrials/frontend/views.py
- clinicaltrials/static/js/site.js
- clinicaltrials/static/scss/site.scss
- clinicaltrials/templates/trial.html
- fabfile.py
> One page per trial

- clinicaltrials/templates/fund.html
Modified 1 line to include reference/link to AllTrials
> Added AllTrials info

- clinicaltrials/frontend/models.py
- clinicaltrials/frontend/tests/common.py
- clinicaltrials/frontend/tests/test_models.py
- clinicaltrials/frontend/views.py
- clinicaltrials/templates/trial.html
> Correctly describe trials with a certificate of exemption.

- clinicaltrials/templates/faq.html
New version of the paper is up so updated throughout.
Fixed some slight display/alignment issues throughout.
> Update paper URL and some fixing some display bugs

- clinicaltrials/frontend/custom_filters.py
- clinicaltrials/frontend/custom_rest_backends.py
- clinicaltrials/frontend/custom_rest_views.py
- clinicaltrials/frontend/models.py
- clinicaltrials/frontend/tests/test_views.py
> Count dropped trials correctly

- clinicaltrials/templates/_base.html
> Add link to blog

- clinicaltrials/frontend/settings.py
- clinicaltrials/frontend/settings_staging.py
- deploy/crontab-fdaaa-update
- deploy/fab_scripts/kickoff_background_data_load.sh
- fabfile.py
Achieved by running update task as www-user
Closes #157
> Fix logfile rotation + permissions problem

- clinicaltrials/frontend/view.sql
Also adds the null `primary_purpose` condition to the `results_due` criteria.
> primary purpose update 2

- clinicaltrials/frontend/management/commands/process_data.py
- clinicaltrials/frontend/tests/fixtures/no_qa.html
- clinicaltrials/frontend/tests/test_import.py
> Handle case where QA results disappear

- clinicaltrials/frontend/views.py
> Don't raise uncaught exceptions on invalid user-data

- clinicaltrials/frontend/management/commands/load_data.py
> Handle null dates in ACT checks

- clinicaltrials/frontend/management/commands/load_data.py
> Be forgiving about nested xml node access

- clinicaltrials/frontend/management/commands/load_data.py
> Don't fail when completion dates are null

- clinicaltrials/templates/faq.html
I have added links and references to The Lancet paper throughout, and changed the email address to the better working ebmdatalab@phc.ox.ac.uk where appropriate.
> Updated with paper info

- clinicaltrials/frontend/context_processors.py
- clinicaltrials/frontend/settings.py
- clinicaltrials/templates/_base.html
- environment-example
So that we can track usage in a privacy-friendly way.
> Replace Google Analytics code with Plausible

- README.md
* try to help the next person to touch this...
> Link to deployment issue from README

- LICENSE.txt
- clinicaltrials/templates/_base.html
- clinicaltrials/templates/faq.html
- holding.html
- Update licence
- Update text
> Replace "EBM DataLab" with "Bennett Institute"

- clinicaltrials/frontend/management/commands/process_data.py
This was already done on master, but the staging env is running on the gae-ise branch
> Update slack messages s/ebmbot/bennett_bot

- clinicaltrials/static/scss/site.scss
- clinicaltrials/templates/_base.html
So that users are notified of the latest status of the website.
> Add notification banner to base template

- clinicaltrials/templates/_base.html
Linked to opensafely-core/sysadmin#175
> Update Plausible JS script tag
